"""Native lifecycle tests. Packaged NSIS/UI routes have their own tests.

The supplied executable here is an inert marker; production only passes the
uninstaller generated by NSIS. No test changes a real game installation.
"""
from __future__ import annotations

import hashlib
import os
import subprocess
from pathlib import Path

import pytest
import test_patcher as fixtures
from test_patcher import dgvoodoo_2872

pytestmark = pytest.mark.skipif(os.name != "nt", reason="Windows lifecycle")
STATE = ".unofficial-shogun-patch"
UNINSTALLER = "Uninstall Unofficial Shogun Patch.exe"


@pytest.fixture(autouse=True)
def remove_test_registration(tmp_path):
    yield
    # Negative cases intentionally retain their removal path. Remove only this
    # fixture's HKCU entries afterwards; keep the on-disk evidence intact.
    import winreg
    parent = r"Software\Microsoft\Windows\CurrentVersion\Uninstall"
    with winreg.OpenKey(winreg.HKEY_CURRENT_USER, parent, 0,
                        winreg.KEY_READ | winreg.KEY_WOW64_32KEY) as key:
        names = [winreg.EnumKey(key, i) for i in range(winreg.QueryInfoKey(key)[0])]
        for name in names:
            if not name.startswith("UnofficialShogunPatch-"):
                continue
            with winreg.OpenKey(key, name) as child:
                try:
                    location = winreg.QueryValueEx(child, "InstallLocation")[0]
                except FileNotFoundError:
                    continue
            if os.path.commonpath([os.path.normcase(str(tmp_path)), os.path.normcase(location)]) == os.path.normcase(str(tmp_path)):
                winreg.DeleteKeyEx(winreg.HKEY_CURRENT_USER, parent + "\\" + name, winreg.KEY_WOW64_32KEY)


def invoke(game: Path, *args: str, cwd: Path | None = None):
    return subprocess.run([str(fixtures.PATCHER), "--target", str(game), *args],
                          cwd=cwd, capture_output=True, text=True, encoding="utf-8", timeout=45)


def marker(tmp_path: Path) -> Path:
    path = tmp_path / "generated-uninstaller.exe"
    path.write_bytes(b"MZ" + b"test uninstaller payload\0" * 64)
    return path


def install(game: Path, payload: Path, fixes="historical", **kwargs):
    result = invoke(game, "--apply", fixes, "--uninstaller", str(payload), **kwargs)
    assert result.returncode == 0, result.stdout + result.stderr
    return result


def inventory(game: Path):
    return {str(p.relative_to(game)): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in game.rglob("*") if p.is_file()}


def registry_key(game: Path):
    import winreg
    parent = r"Software\Microsoft\Windows\CurrentVersion\Uninstall"
    with winreg.OpenKey(winreg.HKEY_CURRENT_USER, parent, 0,
                        winreg.KEY_READ | winreg.KEY_WOW64_32KEY) as key:
        for i in range(winreg.QueryInfoKey(key)[0]):
            name = winreg.EnumKey(key, i)
            if not name.startswith("UnofficialShogunPatch-"):
                continue
            with winreg.OpenKey(key, name) as child:
                location = winreg.QueryValueEx(child, "InstallLocation")[0]
                if os.path.normcase(location) == os.path.normcase(str(game.resolve())):
                    return name, {winreg.EnumValue(child, n)[0]: winreg.EnumValue(child, n)[1]
                                  for n in range(winreg.QueryInfoKey(child)[1])}
    return None


def test_clean_install_uninstall_restores_inventory_and_registration(tmp_path):
    game = fixtures.make_clean_game(tmp_path)
    (game / "saves.dat").write_bytes(b"unrelated personal save")
    before = inventory(game)
    install(game, marker(tmp_path))
    assert (game / UNINSTALLER).is_file()
    entry = registry_key(game)
    assert entry is not None
    assert "Unofficial Shogun" in entry[1]["DisplayName"]
    assert entry[1]["UninstallString"] == f'"{game / UNINSTALLER}"'
    assert entry[1]["QuietUninstallString"] == f'"{game / UNINSTALLER}" /S'
    result = invoke(game, "--uninstall", cwd=tmp_path.parent)
    assert result.returncode == 0, result.stdout + result.stderr
    assert inventory(game) == before
    assert registry_key(game) is None


def test_component_addition_and_noop_keep_first_baseline(tmp_path):
    game = fixtures.make_clean_game(tmp_path)
    before = inventory(game)
    payload = marker(tmp_path)
    install(game, payload, "unit")
    original = (game / STATE / "original" / "0").read_bytes()
    key = registry_key(game)[0]
    install(game, payload, "historical")
    install(game, payload, "historical")
    assert (game / STATE / "original" / "0").read_bytes() == original
    assert registry_key(game)[0] == key
    assert invoke(game, "--uninstall").returncode == 0
    assert inventory(game) == before


def test_legacy_missing_backup_is_reconstructed_without_proprietary_payload(tmp_path):
    game = fixtures.make_clean_game(tmp_path)
    original = (game / "ShogunM.exe").read_bytes()
    result = invoke(game, "--apply", "unit,historical")
    assert result.returncode == 0
    (game / fixtures.SHARED_BACKUP).unlink()
    install(game, marker(tmp_path), "historical")
    assert invoke(game, "--uninstall").returncode == 0
    assert (game / "ShogunM.exe").read_bytes() == original


def test_conflict_requires_choice_then_archives_changed_file(tmp_path):
    game = fixtures.make_clean_game(tmp_path)
    original = (game / "ShogunM.exe").read_bytes()
    install(game, marker(tmp_path))
    current = bytearray((game / "ShogunM.exe").read_bytes())
    current[1024] ^= 1
    changed = bytes(current)
    (game / "ShogunM.exe").write_bytes(changed)
    before = inventory(game)
    result = invoke(game, "--uninstall")
    assert result.returncode == 4, result.stdout + result.stderr
    assert inventory(game) == before
    assert registry_key(game) is not None
    result = invoke(game, "--uninstall", "--archive-conflicts")
    assert result.returncode == 0, result.stdout + result.stderr
    assert (game / "ShogunM.exe").read_bytes() == original
    archives = list(game.glob("Unofficial Shogun Patch recovery*"))
    assert archives and any(p.read_bytes() == changed for d in archives for p in d.rglob("*") if p.is_file())


def test_corrupt_baseline_fails_without_discarding_uninstaller(tmp_path):
    game = fixtures.make_clean_game(tmp_path)
    install(game, marker(tmp_path))
    (game / STATE / "original" / "0").write_bytes(b"corrupt")
    before = inventory(game)
    result = invoke(game, "--uninstall")
    assert result.returncode == 2, result.stdout + result.stderr
    assert inventory(game) == before
    assert registry_key(game) is not None


def test_two_copies_and_unicode_paths_are_independent(tmp_path):
    first = fixtures.make_clean_game(tmp_path)
    second_parent = tmp_path / "Deuxième 日本語"
    second_parent.mkdir()
    second = fixtures.make_clean_game(second_parent)
    payload = marker(tmp_path)
    install(first, payload)
    install(second, payload, "unit")
    second_before = inventory(second)
    assert registry_key(first)[0] != registry_key(second)[0]
    assert invoke(first, "--uninstall", cwd=second).returncode == 0
    assert inventory(second) == second_before
    assert registry_key(second) is not None
    assert invoke(second, "--uninstall").returncode == 0


def test_copied_state_cannot_authorize_different_directory(tmp_path):
    import shutil
    first = fixtures.make_clean_game(tmp_path)
    install(first, marker(tmp_path))
    second = tmp_path / "copied game"
    shutil.copytree(first, second)
    before = inventory(second)
    result = invoke(second, "--uninstall")
    assert result.returncode == 2, result.stdout + result.stderr
    assert inventory(second) == before
    assert invoke(first, "--uninstall").returncode == 0


def test_hardlinked_target_is_refused_without_touching_other_link(tmp_path):
    game = fixtures.make_clean_game(tmp_path)
    external = tmp_path / "external.exe"
    os.link(game / "ShogunM.exe", external)
    before = inventory(game)
    result = invoke(game, "--apply", "historical", "--uninstaller", str(marker(tmp_path)))
    assert result.returncode == 2, result.stdout + result.stderr
    assert inventory(game) == before
    assert external.read_bytes() == (game / "ShogunM.exe").read_bytes()


@pytest.mark.parametrize("fixes", ["recommended", "all", "shutdown", "harvest", "advisor", "retraining-drag", "kawanakajima", "dgvoodoo-resolution"])
def test_component_roundtrip_with_existing_configuration(tmp_path, fixes):
    game = fixtures.make_clean_game(tmp_path)
    (game / "dgVoodoo.conf").write_bytes(fixtures.UNSAFE_DGVOODOO_CONF.encode("ascii"))
    before = inventory(game)
    install(game, marker(tmp_path), fixes)
    assert invoke(game, "--uninstall").returncode == 0
    assert inventory(game) == before


@pytest.mark.parametrize("wrappers", ["absent", "third-party", "identical-bundle"])
def test_full_wrapper_payload_has_proven_before_state(tmp_path, wrappers):
    game = fixtures.make_clean_game(tmp_path)
    vendor = fixtures.PROJECT / "vendor" / "dgvoodoo2"
    for name in ("DDraw.dll", "D3DImm.dll", "D3D9.dll", "dgVoodoo.conf"):
        if wrappers == "third-party":
            (game / name).write_bytes(b"my original " + name.encode())
        elif wrappers == "identical-bundle":
            (game / name).write_bytes((vendor / name).read_bytes())
    before = inventory(game)
    result = invoke(game, "--apply", "all", "--payload", str(vendor), "--uninstaller", str(marker(tmp_path)))
    assert result.returncode == 0, result.stdout + result.stderr
    if wrappers == "identical-bundle":
        assert invoke(game, "--uninstall").returncode == 4
        result = invoke(game, "--uninstall", "--keep-legacy-wrappers")
        assert "warning=legacy_wrappers_retained" in result.stdout
    else:
        result = invoke(game, "--uninstall")
    assert result.returncode == 0, result.stdout + result.stderr
    assert inventory(game) == before


@pytest.mark.parametrize("backup", ["missing", "corrupt", "already-patched"])
def test_legacy_backup_recovery_preserves_unknown_evidence(tmp_path, backup):
    game = fixtures.make_clean_game(tmp_path)
    original = (game / "ShogunM.exe").read_bytes()
    assert invoke(game, "--apply", "unit,historical").returncode == 0
    path = game / fixtures.SHARED_BACKUP
    if backup == "missing":
        path.unlink()
    elif backup == "corrupt":
        path.write_bytes(b"not a game backup")
    else:
        path.write_bytes((game / "ShogunM.exe").read_bytes())
    install(game, marker(tmp_path))
    result = invoke(game, "--uninstall")
    assert result.returncode == 0, result.stdout + result.stderr
    assert (game / "ShogunM.exe").read_bytes() == original
    if backup == "corrupt":
        assert path.read_bytes() == b"not a game backup"
    else:
        assert not path.exists()


@pytest.mark.parametrize("name", [
    "PREVIOUS_RETRAINING_DRAG_PATCHES", "CURRENT_RETRAINING_DRAG_PATCHES",
    "AUDIO_FULL_RETRAINING_DRAG_PATCHES", "REPEAT_RC_RETRAINING_DRAG_PATCHES",
    "MARKER_FREE_RETRAINING_DRAG_PATCHES", "MODEL_STATE_RETRAINING_DRAG_PATCHES",
    "RIGHT_CLICK_SOUND_RETRAINING_DRAG_PATCHES", "CASTLE_TARGET_RETRAINING_DRAG_PATCHES",
    "DIRECT_TARGET_RETRAINING_DRAG_PATCHES", "FULL_ARMY_REJECT_RETRAINING_DRAG_PATCHES",
    "NATIVE_CASTLE_RETRAINING_DRAG_PATCHES", "FULL_CASTLE_REQUEUE_RETRAINING_DRAG_PATCHES",
    "QUEUE_POSITION_RETRAINING_DRAG_PATCHES", "TARGET_TAXONOMY_FINAL_RETRAINING_DRAG_PATCHES",
])
def test_exact_older_retraining_manifest_is_fully_removed(tmp_path, name):
    game = fixtures.make_clean_game(tmp_path)
    path = game / "ShogunM.exe"
    original = path.read_bytes()
    legacy = bytearray(original)
    for offset, _clean, patched in getattr(fixtures, name):
        fixtures.write_bytes(legacy, offset, patched)
    path.write_bytes(legacy)
    install(game, marker(tmp_path), "historical")  # Earlier component is retained by apply, still removed in full.
    result = invoke(game, "--uninstall")
    assert result.returncode == 0, result.stdout + result.stderr
    assert path.read_bytes() == original


def test_legacy_unproven_wrapper_requires_archiving(tmp_path):
    game = fixtures.make_clean_game(tmp_path)
    vendor = fixtures.PROJECT / "vendor" / "dgvoodoo2"
    assert invoke(game, "--apply", "all", "--payload", str(vendor)).returncode == 0
    (game / "DDraw.dll.unofficial-patch.bak").write_bytes(b"corrupt DLL backup")
    install(game, marker(tmp_path), "historical")
    before = inventory(game)
    result = invoke(game, "--uninstall")
    assert result.returncode == 4
    assert inventory(game) == before
    result = invoke(game, "--uninstall", "--archive-conflicts")
    assert result.returncode == 0, result.stdout + result.stderr
    assert not (game / "DDraw.dll").exists()
    assert (game / "DDraw.dll.unofficial-patch.bak").read_bytes() == b"corrupt DLL backup"


def test_case_alias_keeps_same_entry_and_first_baseline(tmp_path):
    game = fixtures.make_clean_game(tmp_path)
    payload = marker(tmp_path)
    install(game, payload)
    key = registry_key(game)[0]
    install(Path(str(game).swapcase()), payload)
    assert registry_key(game)[0] == key
    assert invoke(game, "--uninstall").returncode == 0


def test_missing_executable_uses_receipt_and_explicit_recovery(tmp_path):
    game = fixtures.make_clean_game(tmp_path)
    original = (game / "ShogunM.exe").read_bytes()
    install(game, marker(tmp_path))
    (game / "ShogunM.exe").unlink()
    assert invoke(game, "--uninstall").returncode == 4
    result = invoke(game, "--uninstall", "--archive-conflicts")
    assert result.returncode == 0, result.stdout + result.stderr
    assert (game / "ShogunM.exe").read_bytes() == original


def test_keep_uncertain_wrappers_does_not_override_changed_executable(tmp_path):
    game = fixtures.make_clean_game(tmp_path)
    vendor = fixtures.PROJECT / "vendor" / "dgvoodoo2"
    for name in ("DDraw.dll", "D3DImm.dll", "D3D9.dll", "dgVoodoo.conf"):
        (game / name).write_bytes((vendor / name).read_bytes())
    install(game, marker(tmp_path))
    current = bytearray((game / "ShogunM.exe").read_bytes())
    current[2000] ^= 1
    (game / "ShogunM.exe").write_bytes(current)
    before = inventory(game)
    result = invoke(game, "--uninstall", "--keep-legacy-wrappers")
    assert result.returncode == 4
    assert inventory(game) == before
    result = invoke(game, "--uninstall", "--keep-legacy-wrappers", "--archive-conflicts")
    assert result.returncode == 0, result.stdout + result.stderr
    assert (game / "DDraw.dll").read_bytes() == (vendor / "DDraw.dll").read_bytes()


@pytest.mark.parametrize("valid_game", [True, False])
def test_existing_lock_name_never_deletes_unknown_file(tmp_path, valid_game):
    game = fixtures.make_clean_game(tmp_path)
    if not valid_game:
        (game / "ShogunM.exe").write_bytes(b"not a supported game")
    lock = game / ".unofficial-shogun-patch.lock"
    lock.write_bytes(b"pre-existing unrelated sentinel")
    before = inventory(game)
    result = invoke(game, "--apply", "historical", "--uninstaller", str(marker(tmp_path)))
    assert result.returncode == 2
    assert inventory(game) == before


def test_empty_final_transaction_directory_is_retryable(tmp_path):
    game = fixtures.make_clean_game(tmp_path)
    (game / ".unofficial-shogun-patch-lifecycle").mkdir()
    install(game, marker(tmp_path))
    (game / ".unofficial-shogun-patch-lifecycle").mkdir()
    assert invoke(game, "--uninstall").returncode == 0


@pytest.mark.parametrize("different_hash", [False, True])
def test_wrong_dll_slot_backup_is_retained_and_never_restored(tmp_path, different_hash):
    game = fixtures.make_clean_game(tmp_path)
    vendor = fixtures.PROJECT / "vendor" / "dgvoodoo2"
    assert invoke(game, "--apply", "historical").returncode == 0
    (game / "DDraw.dll").write_bytes((vendor / "DDraw.dll").read_bytes())
    wrong = bytearray((vendor / "D3DImm.dll").read_bytes())
    if different_hash:
        wrong[64] ^= 1  # Still a valid PE32 DLL; exports identify the wrong slot.
    backup = game / "DDraw.dll.unofficial-patch.bak"
    backup.write_bytes(wrong)
    install(game, marker(tmp_path))
    assert invoke(game, "--uninstall").returncode == 4
    result = invoke(game, "--uninstall", "--archive-conflicts")
    assert result.returncode == 0, result.stdout + result.stderr
    assert backup.read_bytes() == wrong
    assert not (game / "DDraw.dll").exists()


@pytest.mark.parametrize("live_bundle", ["old", "current"])
@pytest.mark.parametrize("backup_kind", ["missing", "corrupt", "old-same", "current-same", "old-wrong-slot", "valid-original"])
def test_historical_wrapper_backups_never_become_false_originals(tmp_path, dgvoodoo_2872, live_bundle, backup_kind):
    game = fixtures.make_clean_game(tmp_path)
    vendor = fixtures.PROJECT / "vendor" / "dgvoodoo2"
    source = dgvoodoo_2872 if live_bundle == "old" else vendor
    wrapper = game / "DDraw.dll"
    wrapper.write_bytes((source / wrapper.name).read_bytes())
    backup = game / "DDraw.dll.unofficial-patch.bak"
    data = None
    if backup_kind == "corrupt":
        data = b"not a DLL"
    elif backup_kind == "old-same":
        data = (dgvoodoo_2872 / "DDraw.dll").read_bytes()
    elif backup_kind == "current-same":
        data = (vendor / "DDraw.dll").read_bytes()
    elif backup_kind == "old-wrong-slot":
        data = (dgvoodoo_2872 / "D3DImm.dll").read_bytes()
    elif backup_kind == "valid-original":
        # Synthetic unrelated PE32 wrapper with the right exports: only a DOS
        # stub byte differs. This exercises structural backup validation.
        data = bytearray((dgvoodoo_2872 / "DDraw.dll").read_bytes())
        data[64] ^= 1
        data = bytes(data)
    if data is not None:
        backup.write_bytes(data)
    install(game, marker(tmp_path), "historical")
    before_removal = inventory(game)
    result = invoke(game, "--uninstall")
    if backup_kind == "valid-original":
        assert result.returncode == 0, result.stdout + result.stderr
        assert wrapper.read_bytes() == data
        assert not backup.exists()
    else:
        assert result.returncode == 4, result.stdout + result.stderr
        assert inventory(game) == before_removal
        result = invoke(game, "--uninstall", "--archive-conflicts")
        assert result.returncode == 0, result.stdout + result.stderr
        assert not wrapper.exists()
        if data is not None:
            assert backup.read_bytes() == data
        else:
            assert not backup.exists()
        archived = list(game.glob("Unofficial Shogun Patch recovery */file-3"))
        assert len(archived) == 1
        assert archived[0].read_bytes() == (source / "DDraw.dll").read_bytes()


def test_moved_same_directory_identity_is_refused_until_returned(tmp_path):
    game = fixtures.make_clean_game(tmp_path)
    install(game, marker(tmp_path))
    original_location = game
    moved = tmp_path / "moved game"
    game.rename(moved)
    before = inventory(moved)
    result = invoke(moved, "--uninstall")
    assert result.returncode == 2
    assert "registered_location" in result.stderr
    assert inventory(moved) == before
    moved.rename(original_location)
    assert invoke(original_location, "--uninstall").returncode == 0


def test_unknown_legacy_transaction_content_is_not_deleted(tmp_path):
    game = fixtures.make_clean_game(tmp_path)
    transaction = game / ".unofficial-patch-transaction"
    stage = transaction / "stage"
    stage.mkdir(parents=True)
    (stage / "unrelated-notes.txt").write_bytes(b"user recovery notes")
    (transaction / "journal.bin").write_bytes(b"unknown journal retained too")
    before = inventory(game)
    result = invoke(game, "--apply", "historical", "--uninstaller", str(marker(tmp_path)))
    assert result.returncode == 2
    assert "legacy_transaction_unrecognized_files" in result.stderr
    assert inventory(game) == before
