"""Opt-in tests of removal through the uninstaller generated by the package.

Set SHOGUN_INSTALLER to a built installer. These tests only mutate synthetic
games below pytest's temporary root; they never use a supplied game copy.
SHOGUN_LEGACY_INSTALLER optionally exercises adoption of an older release.

NSIS normally starts a temporary uninstaller and returns from its launcher.
For exit-code assertions we copy the actual generated uninstaller outside the
game and use NSIS's documented ``_?=<game>`` switch (last, unquoted argument).
A separate test runs the actual in-folder executable without that switch and
waits for the durable log and complete file/registration cleanup.
"""
from __future__ import annotations

import ctypes
import base64
import hashlib
import json
import os
from pathlib import Path
import shutil
import stat
import subprocess
import time
from contextlib import contextmanager

import pytest

from test_patcher import make_clean_game
from test_installer_runtime import invoke as invoke_installer

if os.name == "nt":
    import winreg


INSTALLER = os.environ.get("SHOGUN_INSTALLER")
LEGACY_INSTALLER = os.environ.get("SHOGUN_LEGACY_INSTALLER")
UNINSTALLER_NAME = "Uninstall Unofficial Shogun Patch.exe"
STATE_DIRECTORY = ".unofficial-shogun-patch"
UNINSTALL_ROOT = r"Software\Microsoft\Windows\CurrentVersion\Uninstall"
pytestmark = pytest.mark.skipif(
    os.name != "nt" or not INSTALLER,
    reason="Set SHOGUN_INSTALLER on Windows to test the packaged lifecycle",
)


def inventory(root: Path) -> dict[str, str]:
    """Hash every physical fixture file, including unrelated sentinel content."""
    return {
        p.relative_to(root).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
        for p in sorted(root.rglob("*")) if p.is_file()
    }


def save_inventory(path: Path, files: dict[str, str]) -> None:
    path.write_text(json.dumps(files, indent=2, sort_keys=True), encoding="utf-8")


def canonical(path: str | Path) -> str:
    return os.path.normcase(os.path.abspath(path)).rstrip("\\/")


def patch_registrations() -> dict[str, dict[str, object]]:
    """Inspect HKCU's 32-bit uninstall view without changing unrelated entries."""
    entries = {}
    try:
        root = winreg.OpenKey(winreg.HKEY_CURRENT_USER, UNINSTALL_ROOT, 0,
                              winreg.KEY_READ | winreg.KEY_WOW64_32KEY)
    except FileNotFoundError:
        return entries
    with root:
        for index in range(winreg.QueryInfoKey(root)[0]):
            name = winreg.EnumKey(root, index)
            with winreg.OpenKey(root, name) as key:
                values = {}
                for value_index in range(winreg.QueryInfoKey(key)[1]):
                    value_name, value, _ = winreg.EnumValue(key, value_index)
                    values[value_name] = value
            if "unofficial shogun" in str(values.get("DisplayName", "")).lower():
                entries[name] = values
    return entries


def registrations_for(game: Path) -> dict[str, dict[str, object]]:
    return {
        key: value for key, value in patch_registrations().items()
        if value.get("InstallLocation")
        and canonical(str(value["InstallLocation"])) == canonical(game)
    }


def cleanup_owned_registrations(root: Path, before: set[str]) -> None:
    """Cleanup is restricted to new test-created entries under this exact root."""
    for key, values in patch_registrations().items():
        if key in before or not values.get("InstallLocation"):
            continue
        location = canonical(str(values["InstallLocation"]))
        try:
            owned = os.path.commonpath((canonical(root), location)) == canonical(root)
        except ValueError:  # Another task may register a game on a different drive.
            owned = False
        if not owned:
            continue
        winreg.DeleteKeyEx(winreg.HKEY_CURRENT_USER, UNINSTALL_ROOT + "\\" + key,
                           winreg.KEY_WOW64_32KEY, 0)


@pytest.fixture(autouse=True)
def isolate_registration_cleanup(tmp_path: Path):
    before = set(patch_registrations())
    yield
    cleanup_owned_registrations(tmp_path, before)


def fixture_game(root: Path, name: str | None = None) -> Path:
    root.mkdir(parents=True, exist_ok=True)
    game = make_clean_game(root)
    if name:
        destination = root / name
        game.rename(destination)
        game = destination
    for name, data in {
        "SaveGames/personal campaign.sav": b"personal campaign\x00\xff",
        "Screenshots/my battle.bmp": b"personal screenshot",
        "Preferences/player.ini": b"custom preferences\r\n",
        "Mods/unrelated mod.bin": b"unrelated mod bytes",
        "steam_api.dll": b"store client fixture, not a game executable",
        "readme.unofficial-patch.bak": b"unrelated similarly named backup",
    }.items():
        path = game / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    return game


def install(root: Path, game: Path, fixes="recommended", *, installer=None):
    root.mkdir(parents=True, exist_ok=True)
    result, log, text = invoke_installer(root, game, fixes, installer=installer)
    helper = log.parent / "helper.log"
    assert result.returncode == 0, text + (helper.read_text(encoding="utf-8") if helper.exists() else "")
    return log


def assert_registered(game: Path) -> str:
    entries = registrations_for(game)
    assert len(entries) == 1, f"Expected exactly one patch entry for {game}, found {entries}"
    key, values = next(iter(entries.items()))
    assert "unofficial" in str(values["DisplayName"]).lower()
    assert "patch" in str(values["DisplayName"]).lower()
    assert values["DisplayVersion"] == "1.3.2"
    assert values["Publisher"]
    icon = str(values["DisplayIcon"]).split(",")[0].strip('"')
    assert canonical(icon) == canonical(game / UNINSTALLER_NAME)
    for name, expected_arguments in (("UninstallString", ""), ("QuietUninstallString", "/S")):
        command = str(values[name])
        assert command.startswith('"'), "Registered executable paths must be quoted"
        quote_end = command.find('"', 1)
        assert quote_end > 1
        assert canonical(command[1:quote_end]) == canonical(game / UNINSTALLER_NAME)
        assert command[quote_end + 1:].strip() == expected_arguments
    assert values.get("NoModify") == 1 and values.get("NoRepair") == 1
    (game.parent / "patch-registration.json").write_text(
        json.dumps(entries, indent=2, sort_keys=True), encoding="utf-8")
    return key


def uninstall(root: Path, game: Path, *, archive=False, keep_legacy=False,
              direct=False, registered=False, cwd=None):
    """Run the generated binary with its embedded helper, independently of setup."""
    root.mkdir(parents=True, exist_ok=True)
    log_root = root / "removal logs 日本"
    installed = game / UNINSTALLER_NAME
    assert installed.is_file(), "Successful installation must create the named uninstaller"
    executable = installed
    if registered:
        direct = True
    if not direct:
        executable = root / "generated uninstaller.exe"
        shutil.copy2(installed, executable)
    command = f'"{executable}" /S /LOGDIR="{log_root}"'
    if registered:
        entries = registrations_for(game)
        assert len(entries) == 1
        registration = next(iter(entries.values()))
        command = str(registration["QuietUninstallString"]) + f' /LOGDIR="{log_root}"'
    if archive:
        command += " /ARCHIVECHANGES"
    if keep_legacy:
        command += " /KEEPLEGACYWRAPPERS"
    if not direct:
        command += f" _?={game}"
    result = subprocess.run(command, executable=str(executable), cwd=cwd or root,
                            capture_output=True, timeout=90)
    # Direct NSIS launch is asynchronous. Observe the child output, never treat
    # the launcher's zero exit code as evidence that removal completed.
    deadline = time.monotonic() + 45
    while True:
        sessions = list(log_root.glob("*/*.log")) if log_root.exists() else []
        texts = []
        for path in sessions:
            data = path.read_bytes()
            texts.append(data.decode("utf-16" if data.startswith(b"\xff\xfe") else "utf-8", errors="replace"))
        text = "\n".join(texts)
        complete = (
            "result=success operation=uninstall" in text
            and not installed.exists()
            and not registrations_for(game)
            and not (game / ".unofficial-shogun-patch.lock").exists()
        )
        if not direct or complete:
            break
        if time.monotonic() >= deadline:
            pytest.fail(f"Direct uninstaller did not finish cleanup. Launcher exit={result.returncode}\n{text}")
        time.sleep(0.1)
    assert sessions, "Uninstaller must leave persistent diagnostics outside the game"
    if result.returncode == 0:
        assert not (game / STATE_DIRECTORY).exists(), "Completed removal left its active receipt directory"
        assert not (game / ".unofficial-shogun-patch-lifecycle").exists(), "Completed removal left an active transaction"
        assert not (game / ".unofficial-shogun-patch.lock").exists(), "Completed removal left its lifecycle lock"
    return result, text


@pytest.mark.parametrize("fixes", ["historical", "retraining-drag", "throne", "unit", "harvest",
                                   "ammo", "kawanakajima", "odawara", "advisor", "dgvoodoo",
                                   "recommended", "all"])
def test_package_restores_complete_fixture_inventory(tmp_path: Path, fixes: str):
    game = fixture_game(tmp_path)
    before = inventory(game)
    save_inventory(tmp_path / "before.json", before)
    install(tmp_path / "install", game, fixes)
    assert (game / UNINSTALLER_NAME).is_file(), "Installer did not establish removal support"
    assert_registered(game)
    result, text = uninstall(tmp_path / "remove", game)
    assert result.returncode == 0, text
    after = inventory(game)
    save_inventory(tmp_path / "after.json", after)
    assert after == before
    assert not registrations_for(game)


def test_direct_folder_route_survives_deleted_installer_and_different_cwd(tmp_path: Path):
    game = fixture_game(tmp_path, "日本語 game copy with spaces")
    before = inventory(game)
    installer = tmp_path / "downloaded installer.exe"
    shutil.copy2(INSTALLER, installer)
    install(tmp_path / "install", game, "all", installer=installer)
    installer.unlink()
    assert_registered(game)
    result, text = uninstall(tmp_path / "remove", game, direct=True, cwd=tmp_path)
    assert result.returncode == 0, text
    assert inventory(game) == before
    assert not registrations_for(game)


def test_repeated_install_additions_retain_earliest_baseline_and_entry(tmp_path: Path):
    game = fixture_game(tmp_path)
    before = inventory(game)
    install(tmp_path / "first", game, "historical")
    key = assert_registered(game)
    first = inventory(game)
    install(tmp_path / "noop", game, "historical")
    assert assert_registered(game) == key
    assert inventory(game) == first
    install(tmp_path / "addition", game, "kawanakajima,dgvoodoo,advisor")
    assert assert_registered(game) == key
    result, text = uninstall(tmp_path / "remove", game)
    assert result.returncode == 0, text
    assert inventory(game) == before
    install(tmp_path / "reinstall", game, "all")
    assert assert_registered(game) == key
    result, text = uninstall(tmp_path / "remove-again", game)
    assert result.returncode == 0, text
    assert inventory(game) == before


def test_noop_rerun_repairs_missing_uninstaller_and_registration(tmp_path: Path):
    game = fixture_game(tmp_path)
    before = inventory(game)
    install(tmp_path / "first", game, "recommended")
    key = assert_registered(game)
    (game / UNINSTALLER_NAME).unlink()
    install(tmp_path / "repair-executable", game, "recommended")
    assert (game / UNINSTALLER_NAME).is_file()
    assert assert_registered(game) == key
    winreg.DeleteKeyEx(winreg.HKEY_CURRENT_USER, UNINSTALL_ROOT + "\\" + key,
                       winreg.KEY_WOW64_32KEY, 0)
    install(tmp_path / "repair-registration", game, "recommended")
    assert assert_registered(game) == key
    result, text = uninstall(tmp_path / "remove", game)
    assert result.returncode == 0, text
    assert inventory(game) == before


def test_path_case_alias_rerun_uses_the_same_registration(tmp_path: Path):
    game = fixture_game(tmp_path)
    before = inventory(game)
    install(tmp_path / "first", game, "historical")
    key = assert_registered(game)
    installed = inventory(game)
    install(tmp_path / "alias-rerun", Path(str(game).swapcase()), "historical")
    assert assert_registered(game) == key
    assert inventory(game) == installed
    result, text = uninstall(tmp_path / "remove", game)
    assert result.returncode == 0, text
    assert inventory(game) == before


def test_two_games_have_independent_files_and_registrations(tmp_path: Path):
    games = [fixture_game(tmp_path / "a"), fixture_game(tmp_path / "b", "第二 game")]
    original = [inventory(game) for game in games]
    for index, game in enumerate(games):
        install(tmp_path / f"install-{index}", game, "all")
    keys = [assert_registered(game) for game in games]
    assert keys[0] != keys[1]
    untouched = inventory(games[1])
    other_registration = registrations_for(games[1])
    result, text = uninstall(tmp_path / "remove-a", games[0])
    assert result.returncode == 0, text
    assert inventory(games[0]) == original[0]
    assert not registrations_for(games[0])
    assert inventory(games[1]) == untouched
    assert registrations_for(games[1]) == other_registration
    result, text = uninstall(tmp_path / "remove-b", games[1])
    assert result.returncode == 0, text
    assert inventory(games[1]) == original[1]


def test_valid_state_copied_from_another_install_cannot_redirect_removal(tmp_path: Path):
    games = [fixture_game(tmp_path / "first"), fixture_game(tmp_path / "second")]
    originals = [inventory(game) for game in games]
    for index, game in enumerate(games):
        install(tmp_path / f"install-{index}", game, "all")
    states = [game / STATE_DIRECTORY / "state.bin" for game in games]
    valid_second = states[1].read_bytes()
    states[1].write_bytes(states[0].read_bytes())
    before = [inventory(game) for game in games]
    entries = [registrations_for(game) for game in games]
    result, text = uninstall(tmp_path / "reject-other-install-state", games[1])
    assert result.returncode != 0, text
    assert [inventory(game) for game in games] == before
    assert [registrations_for(game) for game in games] == entries
    states[1].write_bytes(valid_second)
    for index, game in enumerate(games):
        result, text = uninstall(tmp_path / f"remove-{index}", game)
        assert result.returncode == 0, text
        assert inventory(game) == originals[index]


def test_registered_quiet_command_targets_its_copy_from_unrelated_cwd(tmp_path: Path):
    game = fixture_game(tmp_path)
    before = inventory(game)
    install(tmp_path / "install", game, "recommended")
    assert_registered(game)
    result, text = uninstall(tmp_path / "registered-route", game, registered=True, cwd=tmp_path)
    assert result.returncode == 0, text
    assert inventory(game) == before
    assert not registrations_for(game)


def test_locked_game_retains_full_removal_path_then_retry_succeeds(tmp_path: Path):
    game = fixture_game(tmp_path)
    original = inventory(game)
    install(tmp_path / "install", game, "recommended")
    patched = inventory(game)
    entry = registrations_for(game)
    kernel = ctypes.WinDLL("kernel32", use_last_error=True)
    kernel.CreateFileW.argtypes = [ctypes.c_wchar_p, ctypes.c_ulong, ctypes.c_ulong,
                                  ctypes.c_void_p, ctypes.c_ulong, ctypes.c_ulong, ctypes.c_void_p]
    kernel.CreateFileW.restype = ctypes.c_void_p
    kernel.CloseHandle.argtypes = [ctypes.c_void_p]
    handle = kernel.CreateFileW(str(game / "ShogunM.exe"), 0x80000000, 1, None, 3, 0, None)
    assert handle != ctypes.c_void_p(-1).value
    try:
        result, text = uninstall(tmp_path / "locked-remove", game)
        assert result.returncode != 0, text
        assert "error=" in text
        assert inventory(game) == patched
        assert registrations_for(game) == entry
    finally:
        kernel.CloseHandle(handle)
    result, text = uninstall(tmp_path / "retry", game)
    assert result.returncode == 0, text
    assert inventory(game) == original
    assert not registrations_for(game)


@pytest.mark.parametrize("mode", ["custom", "identical-vendor", "config-only"])
def test_preexisting_wrappers_are_restored_even_when_bundled_hash_matches(tmp_path: Path, mode: str):
    game = fixture_game(tmp_path)
    vendor = Path(__file__).resolve().parents[1] / "vendor" / "dgvoodoo2"
    for name in ("DDraw.dll", "D3DImm.dll", "D3D9.dll", "dgVoodoo.conf"):
        if mode == "config-only" and name != "dgVoodoo.conf":
            continue
        if mode == "identical-vendor":
            content = (vendor / name).read_bytes()
        elif name == "dgVoodoo.conf":
            content = (b"DefaultEnumeratedResolutions = all\r\n"
                       b"ExtraEnumeratedResolutions = \r\n"
                       b"EnumeratedResolutionBitdepths = all\r\n"
                       b"UserPreference = preserve this\r\n")
        else:
            content = ("pre-existing third-party wrapper " + name).encode("ascii")
        (game / name).write_bytes(content)
    before = inventory(game)
    save_inventory(tmp_path / "before.json", before)
    install(tmp_path / "install", game, "all")
    # The explicit automation override can retain ambiguous pre-existing wrappers.
    result, text = uninstall(tmp_path / "remove", game, keep_legacy=mode == "identical-vendor")
    assert result.returncode == 0, text
    after = inventory(game)
    save_inventory(tmp_path / "after.json", after)
    assert after == before
    assert not registrations_for(game)


@pytest.mark.parametrize("relative", ["ShogunM.exe", "dgVoodoo.conf", "DDraw.dll"])
def test_changed_content_is_automatically_archived_with_exact_user_bytes(tmp_path: Path, relative: str):
    game = fixture_game(tmp_path)
    original = inventory(game)
    install(tmp_path / "install", game, "all")
    changed = (game / relative).read_bytes() + b"\r\nuser or another mod changed this file\r\n"
    (game / relative).write_bytes(changed)
    result, text = uninstall(tmp_path / "archive-and-remove", game)
    assert result.returncode == 0, text
    archives = list(game.glob("Unofficial Shogun Patch recovery *"))
    assert len(archives) == 1
    archived = [p for p in archives[0].rglob("*") if p.is_file()]
    assert any(p.read_bytes() == changed for p in archived), "Automatic recovery must preserve exact changed bytes"
    assert any("readme" in p.name.lower() for p in archived), "Recovery archive needs an explanation"
    after = inventory(game)
    baseline_after = {path: digest for path, digest in after.items()
                      if not path.startswith(archives[0].name + "/")}
    assert baseline_after == original
    assert not registrations_for(game)
    save_inventory(tmp_path / "restored-with-recovery.json", after)


@pytest.mark.parametrize("damage", ["state-corrupt", "original-corrupt", "original-missing"])
def test_unusable_removal_state_fails_without_discarding_retry_material(tmp_path: Path, damage: str):
    game = fixture_game(tmp_path)
    original = inventory(game)
    install(tmp_path / "install", game, "all")
    state = game / STATE_DIRECTORY
    target = state / ("state.bin" if damage == "state-corrupt" else "original/0")
    valid = target.read_bytes()
    if damage == "original-missing":
        target.unlink()
    else:
        target.write_bytes(b"invalid recovery data")
    damaged = inventory(game)
    entry = registrations_for(game)
    result, text = uninstall(tmp_path / "failed-remove", game)
    assert result.returncode != 0, text
    assert "error=" in text
    assert inventory(game) == damaged
    assert registrations_for(game) == entry
    target.write_bytes(valid)
    result, text = uninstall(tmp_path / "retry", game)
    assert result.returncode == 0, text
    assert inventory(game) == original


def test_unrelated_file_at_uninstaller_name_is_not_overwritten(tmp_path: Path):
    game = fixture_game(tmp_path)
    (game / UNINSTALLER_NAME).write_bytes(b"unrelated user file occupying the requested path")
    before = inventory(game)
    result, log, text = invoke_installer(tmp_path / "install", game, "recommended")
    assert result.returncode != 0, text
    assert inventory(game) == before
    assert not registrations_for(game)


def test_missing_installed_executable_is_automatically_restored(tmp_path: Path):
    game = fixture_game(tmp_path)
    original = inventory(game)
    install(tmp_path / "install", game, "all")
    (game / "ShogunM.exe").unlink()
    result, text = uninstall(tmp_path / "restore-missing", game)
    assert result.returncode == 0, text
    after = {path: digest for path, digest in inventory(game).items()
             if not path.startswith("Unofficial Shogun Patch recovery ")}
    assert after == original
    assert not registrations_for(game)


@pytest.mark.parametrize("relative", ["ShogunM.exe", f"{STATE_DIRECTORY}/original/0",
                                     f"{STATE_DIRECTORY}/state.bin"])
def test_uninstall_rejects_hardlinked_targets_or_recovery_files(tmp_path: Path, relative: str):
    game = fixture_game(tmp_path)
    original = inventory(game)
    install(tmp_path / "install", game, "all")
    outside = tmp_path / "unrelated-hardlink"
    os.link(game / relative, outside)
    before = inventory(game)
    outside_before = outside.read_bytes()
    entry = registrations_for(game)
    try:
        result, text = uninstall(tmp_path / "reject-link", game)
        assert result.returncode != 0, text
        assert inventory(game) == before
        assert outside.read_bytes() == outside_before
        assert registrations_for(game) == entry
    finally:
        outside.unlink()
    result, text = uninstall(tmp_path / "retry", game)
    assert result.returncode == 0, text
    assert inventory(game) == original


def junction(link: Path, target: Path) -> None:
    result = subprocess.run(["cmd.exe", "/d", "/c", "mklink", "/J", str(link), str(target)],
                            capture_output=True, timeout=10)
    assert result.returncode == 0, result.stdout + result.stderr
    assert is_junction(link)


def is_junction(path: Path) -> bool:
    return path.lstat().st_reparse_tag == stat.IO_REPARSE_TAG_MOUNT_POINT


def test_installer_rejects_junction_target_without_touching_destination(tmp_path: Path):
    game = fixture_game(tmp_path / "real")
    before = inventory(game)
    link = tmp_path / "redirected game"
    junction(link, game)
    try:
        result, log, text = invoke_installer(tmp_path / "install", link, "all")
        assert result.returncode != 0, text
        assert inventory(game) == before
        assert not registrations_for(game)
        assert not registrations_for(link)
    finally:
        # RemoveDirectoryW removes this verified junction, never its target.
        assert is_junction(link)
        link.rmdir()


def test_uninstaller_rejects_junction_recovery_directory_and_preserves_external_files(tmp_path: Path):
    game = fixture_game(tmp_path)
    original = inventory(game)
    install(tmp_path / "install", game, "all")
    baseline = game / STATE_DIRECTORY / "original"
    displaced = tmp_path / "external originals"
    baseline.rename(displaced)
    junction(baseline, displaced)
    before_external = inventory(displaced)
    entry = registrations_for(game)
    try:
        result, text = uninstall(tmp_path / "reject-junction", game)
        assert result.returncode != 0, text
        assert inventory(displaced) == before_external
        assert registrations_for(game) == entry
        assert (game / UNINSTALLER_NAME).is_file()
    finally:
        assert is_junction(baseline)
        baseline.rmdir()
        displaced.rename(baseline)
    result, text = uninstall(tmp_path / "retry", game)
    assert result.returncode == 0, text
    assert inventory(game) == original


@pytest.mark.skipif(not LEGACY_INSTALLER, reason="Set SHOGUN_LEGACY_INSTALLER for packaged legacy migration")
@pytest.mark.parametrize("fixes", ["historical", "kawanakajima", "all"])
def test_legacy_patch_gains_removal_support_without_losing_original_baseline(tmp_path: Path, fixes: str):
    game = fixture_game(tmp_path)
    original = inventory(game)
    install(tmp_path / "legacy", game, fixes, installer=LEGACY_INSTALLER)
    assert not (game / UNINSTALLER_NAME).exists()
    # New selections may be a no-op or a subset of the earlier patch: removal
    # must cover the entire adopted installation, not only this invocation.
    install(tmp_path / "adopt", game, "historical")
    assert_registered(game)
    result, text = uninstall(tmp_path / "remove", game)
    assert result.returncode == 0, text
    after = inventory(game)
    remaining = {path: digest for path, digest in after.items()
                 if not path.startswith("Unofficial Shogun Patch recovery ")}
    assert remaining == original
    assert not registrations_for(game)
    save_inventory(tmp_path / "legacy-original.json", original)
    save_inventory(tmp_path / "legacy-restored.json", after)


@pytest.mark.skipif(not LEGACY_INSTALLER, reason="Set SHOGUN_LEGACY_INSTALLER for packaged wrapper-only migration")
@pytest.mark.parametrize("keep", [False, True], ids=["archive", "keep"])
def test_wrapper_only_legacy_adoption_archives_by_default_with_keep_override(tmp_path: Path, keep: bool):
    game = fixture_game(tmp_path)
    original = inventory(game)
    install(tmp_path / "legacy-wrapper", game, "dgvoodoo", installer=LEGACY_INSTALLER)
    legacy = inventory(game)
    install(tmp_path / "adopt", game, "historical")
    result, text = uninstall(tmp_path / "remove", game, keep_legacy=keep)
    assert result.returncode == 0, text
    after = inventory(game)
    baseline_after = {name: digest for name, digest in after.items()
                      if not name.startswith("Unofficial Shogun Patch recovery ")}
    assert baseline_after == (legacy if keep else original)
    if keep:
        assert "legacy_wrappers_retained" in text
    else:
        assert any(name.startswith("Unofficial Shogun Patch recovery ") for name in after)
        archived_hashes = {digest for name, digest in after.items()
                           if name.startswith("Unofficial Shogun Patch recovery ")}
        for name in ("DDraw.dll", "D3DImm.dll", "D3D9.dll", "dgVoodoo.conf"):
            assert legacy[name] in archived_hashes, f"Automatic removal must preserve {name}"
    assert not registrations_for(game)


class FixtureDacl:
    """DACL-only test operations; no backup/restore privilege or owner changes."""

    def __init__(self):
        self.adv = ctypes.WinDLL("advapi32", use_last_error=True)
        self.kernel = ctypes.WinDLL("kernel32", use_last_error=True)
        pointer = ctypes.c_void_p
        pointer_ref = ctypes.POINTER(pointer)
        dword = ctypes.c_ulong
        self.adv.GetNamedSecurityInfoW.argtypes = [ctypes.c_wchar_p, ctypes.c_int, dword,
                                                  pointer_ref, pointer_ref, pointer_ref, pointer_ref, pointer_ref]
        self.adv.GetNamedSecurityInfoW.restype = dword
        self.adv.SetNamedSecurityInfoW.argtypes = [ctypes.c_wchar_p, ctypes.c_int, dword,
                                                  pointer, pointer, pointer, pointer]
        self.adv.SetNamedSecurityInfoW.restype = dword
        self.adv.SetFileSecurityW.argtypes = [ctypes.c_wchar_p, dword, pointer]
        self.adv.GetSecurityDescriptorLength.argtypes = [pointer]
        self.adv.GetSecurityDescriptorLength.restype = dword
        self.adv.GetSecurityDescriptorDacl.argtypes = [pointer, ctypes.POINTER(ctypes.c_int),
                                                      pointer_ref, ctypes.POINTER(ctypes.c_int)]
        self.adv.GetSecurityDescriptorControl.argtypes = [pointer, ctypes.POINTER(ctypes.c_ushort),
                                                         ctypes.POINTER(dword)]
        self.adv.ConvertSecurityDescriptorToStringSecurityDescriptorW.argtypes = [pointer, dword, dword,
                                                                                 pointer_ref, ctypes.POINTER(dword)]
        self.adv.ConvertStringSecurityDescriptorToSecurityDescriptorW.argtypes = [ctypes.c_wchar_p, dword,
                                                                                 pointer_ref, ctypes.POINTER(dword)]
        self.adv.OpenProcessToken.argtypes = [pointer, dword, pointer_ref]
        self.adv.GetTokenInformation.argtypes = [pointer, ctypes.c_int, pointer, dword, ctypes.POINTER(dword)]
        self.adv.ConvertSidToStringSidW.argtypes = [pointer, pointer_ref]
        self.kernel.GetCurrentProcess.restype = pointer
        self.kernel.CloseHandle.argtypes = [pointer]
        self.kernel.LocalFree.argtypes = [pointer]
        self.kernel.LocalFree.restype = pointer

    def current_sid(self) -> str:
        token, string = ctypes.c_void_p(), ctypes.c_void_p()
        needed = ctypes.c_ulong()
        if not self.adv.OpenProcessToken(self.kernel.GetCurrentProcess(), 8, ctypes.byref(token)):
            raise ctypes.WinError(ctypes.get_last_error())
        try:
            self.adv.GetTokenInformation(token, 1, None, 0, ctypes.byref(needed))
            data = ctypes.create_string_buffer(needed.value)
            if not self.adv.GetTokenInformation(token, 1, data, needed, ctypes.byref(needed)):
                raise ctypes.WinError(ctypes.get_last_error())
            sid = ctypes.c_void_p.from_buffer(data)
            if not self.adv.ConvertSidToStringSidW(sid, ctypes.byref(string)):
                raise ctypes.WinError(ctypes.get_last_error())
            return ctypes.wstring_at(string)
        finally:
            if string.value:
                self.kernel.LocalFree(string)
            self.kernel.CloseHandle(token)

    def from_sddl(self, sddl: str) -> bytes:
        descriptor, size = ctypes.c_void_p(), ctypes.c_ulong()
        if not self.adv.ConvertStringSecurityDescriptorToSecurityDescriptorW(
                sddl, 1, ctypes.byref(descriptor), ctypes.byref(size)):
            raise ctypes.WinError(ctypes.get_last_error())
        try:
            return ctypes.string_at(descriptor, size.value)
        finally:
            self.kernel.LocalFree(descriptor)

    def snapshot(self, path: Path) -> dict:
        descriptor, dacl, string = ctypes.c_void_p(), ctypes.c_void_p(), ctypes.c_void_p()
        status = self.adv.GetNamedSecurityInfoW(str(path), 1, 4, None, None,
                                               ctypes.byref(dacl), None, ctypes.byref(descriptor))
        if status:
            raise ctypes.WinError(status)
        try:
            control, revision = ctypes.c_ushort(), ctypes.c_ulong()
            if not self.adv.GetSecurityDescriptorControl(descriptor, ctypes.byref(control), ctypes.byref(revision)):
                raise ctypes.WinError(ctypes.get_last_error())
            if not self.adv.ConvertSecurityDescriptorToStringSecurityDescriptorW(
                    descriptor, 1, 4, ctypes.byref(string), None):
                raise ctypes.WinError(ctypes.get_last_error())
            return {"descriptor": base64.b64encode(ctypes.string_at(
                        descriptor, self.adv.GetSecurityDescriptorLength(descriptor))).decode("ascii"),
                    "sddl": ctypes.wstring_at(string), "control": control.value}
        finally:
            if string.value:
                self.kernel.LocalFree(string)
            self.kernel.LocalFree(descriptor)

    def apply(self, path: Path, descriptor: bytes, *, exact_control=False) -> None:
        buffer = ctypes.create_string_buffer(descriptor)
        dacl = ctypes.c_void_p()
        present, defaulted = ctypes.c_int(), ctypes.c_int()
        control, revision = ctypes.c_ushort(), ctypes.c_ulong()
        if not self.adv.GetSecurityDescriptorDacl(buffer, ctypes.byref(present), ctypes.byref(dacl),
                                                 ctypes.byref(defaulted)):
            raise ctypes.WinError(ctypes.get_last_error())
        assert present.value, "Fixture must have an explicit security descriptor DACL"
        if not self.adv.GetSecurityDescriptorControl(buffer, ctypes.byref(control), ctypes.byref(revision)):
            raise ctypes.WinError(ctypes.get_last_error())
        inheritance = 0x80000000 if control.value & 0x1000 else 0x20000000
        status = self.adv.SetNamedSecurityInfoW(str(path), 1, 4 | inheritance, None, None, dacl, None)
        if status:
            raise ctypes.WinError(status)
        if exact_control and self.snapshot(path)["control"] != control.value:
            # SetNamedSecurityInfo upgrades old ACLs to the automatic inheritance
            # model. Its DACL-only low-level counterpart restores the saved mode
            # without propagating another change into descendants. WRITE_DAC is
            # sufficient; no SeRestorePrivilege, owner or SACL operation is used.
            # https://learn.microsoft.com/windows/win32/secauthz/automatic-propagation-of-inheritable-aces
            if not self.adv.SetFileSecurityW(str(path), 4, buffer):
                raise ctypes.WinError(ctypes.get_last_error())


@contextmanager
def read_only_fixture_acl(game: Path, evidence_root: Path):
    """Restrict only this fixture; restore each saved DACL using owner rights."""
    evidence_root.mkdir()
    paths = sorted([game, *game.rglob("*")], key=lambda path: (len(path.parts), str(path)))
    assert all(not (path.lstat().st_file_attributes & 0x400) for path in paths)
    acl = FixtureDacl()
    saved = [(path, acl.snapshot(path)) for path in paths]
    (evidence_root / "original-dacls.json").write_text(json.dumps(
        {str(path.relative_to(game)): snapshot for path, snapshot in saved}, indent=2), encoding="utf-8")
    # Grant this exact account read/execute and WRITE_DAC for restoration. The
    # installer cannot write file data, delete files or create its lifecycle lock.
    # Do not assume the filtered token has the built-in Users group enabled.
    readonly = acl.from_sddl(f"D:P(A;;FA;;;BA)(A;;0x001600A9;;;{acl.current_sid()})")
    try:
        for path in paths:
            acl.apply(path, readonly)
        (evidence_root / "restriction.json").write_text(json.dumps(
            {str(path.relative_to(game)): acl.snapshot(path)["sddl"] for path in paths}, indent=2), encoding="utf-8")
        yield
    finally:
        restored, errors = {}, []
        for path, snapshot in saved:
            try:
                acl.apply(path, base64.b64decode(snapshot["descriptor"]), exact_control=True)
                current = acl.snapshot(path)
                restored[str(path.relative_to(game))] = current
                if current["sddl"] != snapshot["sddl"] or current["control"] != snapshot["control"]:
                    errors.append(f"DACL/inheritance mismatch: {path}")
            except Exception as error:
                errors.append(f"{path}: {error}")
        (evidence_root / "restoration.json").write_text(json.dumps(
            {"objects": restored, "errors": errors}, indent=2), encoding="utf-8")
        assert not errors, errors


@pytest.mark.parametrize("operation", ["install", "uninstall"])
def test_ordinary_user_denied_game_acl_is_truthful_and_retryable(tmp_path: Path, operation: str):
    if ctypes.windll.shell32.IsUserAnAdmin():
        pytest.skip("Requires an ordinary/medium user token; elevated Administrators intentionally retain full access")
    game = fixture_game(tmp_path)
    original = inventory(game)
    if operation == "uninstall":
        install(tmp_path / "install", game, "recommended")
    before = inventory(game)
    entry = registrations_for(game)
    with read_only_fixture_acl(game, tmp_path / "acl-evidence"):
        if operation == "install":
            result, log, text = invoke_installer(tmp_path / "denied-install", game, "recommended")
            text += (log.parent / "helper.log").read_text(encoding="utf-8")
        else:
            result, text = uninstall(tmp_path / "denied-remove", game)
        assert result.returncode == 2, text
        assert "error=lifecycle_busy_or_denied" in text and "win32=5" in text
        assert inventory(game) == before
        assert registrations_for(game) == entry
    if operation == "install":
        install(tmp_path / "retry-install", game, "recommended")
    result, text = uninstall(tmp_path / "retry-remove", game)
    assert result.returncode == 0, text
    assert inventory(game) == original
